name: Create Release Artifact

on:
    pull_request:
        types: [closed]
        branches:
            - release

jobs:
    build-artifact:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20


            - name: Install npm packages
              run: npm install -g rollup terser

            - name: Consolidation and Minification
              run: |
                mkdir ../release
                rollup index.js --file ../release/index.js --format esm --no-treeshake
                echo "File Consolidated"
                terser ../release/index.js -o ../release/index.js --compress --comments '/^\*(.*?)/'
                echo "Minified file in-place"

            - name: Bring essentianls
              run: |
                cp -f README.md ../release/ || true
                cp -f LICENSE ../release/ || true
                cp -f package.json ../release/ || true

            - name: Create archive
              run: |
                rm -rf ../${{ github.event.repository.name }}
                mv ../release ../${{ github.event.repository.name }}
                tar -czvf /tmp/${{ github.event.repository.name }}.tar.gz -C .. ${{ github.event.repository.name }}

            - name: Upload artifact
              uses: actions/upload-artifact@v6
              with:
                name: production-build
                path: /tmp/${{ github.event.repository.name }}.tar.gz

            - name: Create Release
              if: github.event.pull_request.merged == true
              uses: softprops/action-gh-release@v2
              with:
                tag_name: release-${{ github.run_number }}
                name: Release
                files: /tmp/${{ github.event.repository.name }}.tar.gz
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Keep lastest release only
              uses: dev-drprasad/delete-older-releases@v0.3.4   # this is no longer maintained
              with:
                keep_latest: 1
                delete_tags: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}